[env:nodemcu]

platform = espressif8266
board = nodemcu
framework = arduino

monitor_speed = 115200

#upload_protocol = espota
#upload_port = 192.168.0.148
#upload_flags =
#    --port=8266


board_build.filesystem = littlefs

; Fix for some ESP8266 flash chips
board_build.flash_mode = dout


extra_scripts = pre:extra_script.py


lib_deps =
    RTClib
    NTPClient
    ArduinoJson
    PubSubClient
    LiquidCrystal_I2C
    ESPAsyncWebServer-esphome
    DFRobotDFPlayerMini
    EspSoftwareSerial
    SPI
    Adafruit BusIO